import type { Opportunity, PipelineHealth } from "@/lib/types";

export const demoOpportunities: Opportunity[] = [
  {
    id: "demo-01",
    slug: "new-realities-film-lab",
    title: "New Realities Film Lab",
    organizer: "Future Frame Institute",
    category: "Residency",
    status: "closing-soon",
    aiPolicy: "allowed",
    deadline: "2026-09-28T23:59:00Z",
    opensAt: "2026-08-12T00:00:00Z",
    prizeAmount: 12000,
    prizeCurrency: "EUR",
    entryFeeAmount: 0,
    entryFeeCurrency: "EUR",
    location: "Berlin, Germany",
    remote: false,
    maxRuntimeMinutes: 20,
    sourceUrl: "https://example.com/new-realities",
    officialUrl: "https://example.com/new-realities",
    sourceType: "official",
    confidence: 0.98,
    summary:
      "A six-week development residency for short films using generative tools in production, post-production or performance.",
    eligibility: ["International", "Teams of 1–4", "Work in development"],
    formats: ["Short film", "Hybrid", "Experimental"],
    tags: ["development", "mentorship", "travel covered"],
    discoveredAt: "2026-09-18T08:15:00Z",
    verifiedAt: "2026-09-18T09:02:00Z",
    featured: true,
    demo: true,
  },
  {
    id: "demo-02",
    slug: "synthetic-cinema-prize",
    title: "Synthetic Cinema Prize",
    organizer: "Aperture Next",
    category: "AI film festival",
    status: "open",
    aiPolicy: "required",
    deadline: "2026-10-16T23:59:00Z",
    opensAt: "2026-09-01T00:00:00Z",
    prizeAmount: 25000,
    prizeCurrency: "USD",
    entryFeeAmount: 0,
    entryFeeCurrency: "USD",
    location: "Los Angeles, USA",
    remote: true,
    maxRuntimeMinutes: 12,
    sourceUrl: "https://example.com/synthetic-cinema",
    officialUrl: "https://example.com/synthetic-cinema",
    sourceType: "official",
    confidence: 0.96,
    summary:
      "International competition for narrative and documentary shorts with substantial generative-video authorship.",
    eligibility: ["International", "Completed after Jan 2026"],
    formats: ["Narrative", "Documentary", "Animation"],
    tags: ["cash prize", "screening", "AI required"],
    discoveredAt: "2026-09-16T17:30:00Z",
    verifiedAt: "2026-09-16T18:10:00Z",
    featured: true,
    demo: true,
  },
  {
    id: "demo-03",
    slug: "moving-image-open-call",
    title: "Moving Image Open Call",
    organizer: "North Sea Arts Forum",
    category: "Traditional festival",
    status: "open",
    aiPolicy: "allowed",
    deadline: "2026-11-02T23:59:00Z",
    opensAt: "2026-08-25T00:00:00Z",
    prizeAmount: 5000,
    prizeCurrency: "EUR",
    entryFeeAmount: 18,
    entryFeeCurrency: "EUR",
    location: "Rotterdam, Netherlands",
    remote: false,
    maxRuntimeMinutes: 30,
    sourceUrl: "https://example.com/moving-image",
    officialUrl: "https://example.com/moving-image",
    sourceType: "official",
    confidence: 0.95,
    summary:
      "Curated moving-image programme accepting AI-assisted work when process and source material are disclosed.",
    eligibility: ["International", "Premiere preferred"],
    formats: ["Experimental", "Documentary", "Installation"],
    tags: ["traditional festival", "AI disclosure"],
    discoveredAt: "2026-09-12T10:00:00Z",
    verifiedAt: "2026-09-12T11:20:00Z",
    demo: true,
  },
  {
    id: "demo-04",
    slug: "motion-model-challenge",
    title: "Motion Model Challenge",
    organizer: "Vector Motion",
    category: "Platform challenge",
    status: "open",
    aiPolicy: "required",
    deadline: "2026-10-07T18:00:00Z",
    opensAt: "2026-09-20T00:00:00Z",
    prizeAmount: 10000,
    prizeCurrency: "USD",
    entryFeeAmount: 0,
    entryFeeCurrency: "USD",
    location: "Online",
    remote: true,
    maxRuntimeMinutes: 3,
    sourceUrl: "https://example.com/motion-model",
    officialUrl: "https://example.com/motion-model",
    sourceType: "official",
    confidence: 0.99,
    summary:
      "A fast-turnaround platform challenge for short visual stories created with the organizer’s latest video model.",
    eligibility: ["International", "Platform account required"],
    formats: ["Micro-short", "Music video", "Commercial"],
    tags: ["credits", "cash prize", "three minutes"],
    discoveredAt: "2026-09-20T06:20:00Z",
    verifiedAt: "2026-09-20T06:42:00Z",
    featured: true,
    demo: true,
  },
  {
    id: "demo-05",
    slug: "cinema-prototype-fund",
    title: "Cinema Prototype Fund",
    organizer: "Open Culture Foundation",
    category: "Grant",
    status: "verified",
    aiPolicy: "allowed",
    deadline: "2026-11-20T12:00:00Z",
    opensAt: "2026-10-01T00:00:00Z",
    prizeAmount: 20000,
    prizeCurrency: "EUR",
    entryFeeAmount: 0,
    entryFeeCurrency: "EUR",
    location: "European Union",
    remote: true,
    maxRuntimeMinutes: null,
    sourceUrl: "https://example.com/prototype-fund",
    officialUrl: "https://example.com/prototype-fund",
    sourceType: "official",
    confidence: 0.94,
    summary:
      "Prototype funding for European filmmakers exploring new production methods, audience formats and responsible AI.",
    eligibility: ["EU residents", "Independent creators"],
    formats: ["Prototype", "Short film", "Interactive"],
    tags: ["grant", "prototype", "EU"],
    discoveredAt: "2026-09-17T12:10:00Z",
    verifiedAt: "2026-09-19T08:10:00Z",
    demo: true,
  },
  {
    id: "demo-06",
    slug: "brand-story-awards",
    title: "Brand Story Awards",
    organizer: "Creative Commerce Guild",
    category: "Advertising competition",
    status: "open",
    aiPolicy: "allowed",
    deadline: "2026-12-01T23:59:00Z",
    opensAt: "2026-09-05T00:00:00Z",
    prizeAmount: 8000,
    prizeCurrency: "GBP",
    entryFeeAmount: 35,
    entryFeeCurrency: "GBP",
    location: "London, UK",
    remote: true,
    maxRuntimeMinutes: 2,
    sourceUrl: "https://example.com/brand-story",
    officialUrl: "https://example.com/brand-story",
    sourceType: "official",
    confidence: 0.93,
    summary:
      "Commercial storytelling competition with a dedicated emerging-tech category and transparent rights terms.",
    eligibility: ["International", "Student and professional tracks"],
    formats: ["Advertisement", "Branded short"],
    tags: ["commercial", "brief", "rights checked"],
    discoveredAt: "2026-09-14T09:40:00Z",
    verifiedAt: "2026-09-15T07:50:00Z",
    demo: true,
  },
  {
    id: "demo-07",
    slug: "future-frames-rumor",
    title: "Future Frames Creator Call",
    organizer: "Future Frames",
    category: "Platform challenge",
    status: "signal",
    aiPolicy: "unclear",
    deadline: null,
    opensAt: null,
    prizeAmount: null,
    prizeCurrency: null,
    entryFeeAmount: null,
    entryFeeCurrency: null,
    location: "Online",
    remote: true,
    maxRuntimeMinutes: null,
    sourceUrl: "https://example.com/future-frames-news",
    officialUrl: null,
    sourceType: "press",
    confidence: 0.61,
    summary:
      "An organizer interview points to a creator competition next month. No submission page is available yet.",
    eligibility: ["Not announced"],
    formats: ["Not announced"],
    tags: ["early signal", "watching"],
    discoveredAt: "2026-09-21T07:05:00Z",
    verifiedAt: null,
    demo: true,
  },
  {
    id: "demo-08",
    slug: "algorithmic-visions-student",
    title: "Algorithmic Visions Student Showcase",
    organizer: "Milan Media School",
    category: "AI film festival",
    status: "discovered",
    aiPolicy: "required",
    deadline: "2026-10-31T23:59:00Z",
    opensAt: "2026-09-15T00:00:00Z",
    prizeAmount: 3000,
    prizeCurrency: "EUR",
    entryFeeAmount: 0,
    entryFeeCurrency: "EUR",
    location: "Milan, Italy",
    remote: false,
    maxRuntimeMinutes: 10,
    sourceUrl: "https://example.com/algorithmic-visions",
    officialUrl: null,
    sourceType: "community",
    confidence: 0.74,
    summary:
      "A student-focused screening call found through a community lead; official rules are awaiting confirmation.",
    eligibility: ["Current students", "Graduated in 2026"],
    formats: ["Short film", "Animation"],
    tags: ["student", "Italy", "verification pending"],
    discoveredAt: "2026-09-21T05:50:00Z",
    verifiedAt: null,
    demo: true,
  },
];

export const demoPipelineHealth: PipelineHealth = {
  lastDiscoveryAt: "2026-09-21T08:10:00Z",
  lastMonitorAt: "2026-09-21T09:00:00Z",
  sourcesTracked: 286,
  leadsPending: 14,
  recordsOpen: 47,
  demoMode: true,
};
