-- Weekly team brief (ROADMAP priority 4). Generated by
-- scripts/cineradar/weekly-brief.mjs from stored records only; read by the
-- authenticated /team pages with the service role. Never public.

create table if not exists public.weekly_briefs (
  id uuid primary key default gen_random_uuid(),
  week_start date not null unique,
  generated_at timestamptz not null default now(),
  status text not null default 'draft' check (status in ('draft', 'approved', 'sent')),
  stats jsonb not null default '{}'::jsonb check (jsonb_typeof(stats) = 'object'),
  text_body text not null default '',
  approved_by text,
  approved_at timestamptz
);

create table if not exists public.weekly_brief_items (
  id uuid primary key default gen_random_uuid(),
  brief_id uuid not null references public.weekly_briefs(id) on delete cascade,
  section text not null check (section in ('action_now', 'new_high_value', 'for_our_films', 'changed', 'watch')),
  position integer not null check (position >= 0),
  opportunity_id uuid references public.opportunities(id) on delete set null,
  slug text,
  title text not null check (btrim(title) <> ''),
  organizer text,
  reason text not null default '',
  action text,
  priority integer not null default 0,
  unique (brief_id, position)
);

create index if not exists idx_weekly_brief_items_brief on public.weekly_brief_items (brief_id, position);

alter table public.weekly_briefs enable row level security;
alter table public.weekly_brief_items enable row level security;
revoke all on public.weekly_briefs from anon, authenticated;
revoke all on public.weekly_brief_items from anon, authenticated;
